USE lab_mysql;

CREATE TABLE Cars
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
VIN CHAR(17) NOT NULL,
Manufacturer VARCHAR(255),
Model VARCHAR(255),
Year INTEGER(4),
Color VARCHAR(255)
);

CREATE TABLE Customers
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Customer_ID INT(5) NOT NULL,
Name VARCHAR(255),
Phone CHAR(12),
Email VARCHAR(255),
Address VARCHAR(255),
City VARCHAR(255),
State_Province VARCHAR(255),
Country VARCHAR(255),
Postal INTEGER(6)
);

CREATE TABLE Salespersons
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Staff_ID INT(5) NOT NULL,
Name VARCHAR(255),
Store VARCHAR(255)
);

CREATE TABLE Invoices
(
ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Invoice_Nr INT(9) NOT NULL,
Date DATE,
Car INTEGER,
Customer INTEGER,
Salesperson INTEGER
);
