USE lab_mysql;

CREATE TABLE Cars (
ID int AUTO_INCREMENT,
CAR_ID VARCHAR(255),
MANUFACTURER VARCHAR(255),
MODEL VARCHAR(255),
CAR_YEAR INT,
COLOUR VARCHAR(255),
PRIMARY KEY (ID));

CREATE TABLE Customers (
ID int AUTO_INCREMENT,
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(255),
PHONE_NUMBER VARCHAR(255),
EMAIL VARCHAR(255),
ADDRESS VARCHAR(255),
CITY VARCHAR(255),
STATE VARCHAR(255),
COUNTRY VARCHAR(255),
POST_CODE VARCHAR(255),
PRIMARY KEY (ID));

CREATE TABLE Sales_People(
ID int AUTO_INCREMENT,
STAFF_ID INT,
SALESPERSON_NAME VARCHAR(255),
STORE_NAME VARCHAR(255),
PRIMARY KEY (ID));

CREATE TABLE Invoices(
ID int AUTO_INCREMENT,
INVOICE_NUMBER INT,
INVOICE_DATE DATE,
CAR INT,
CUSTOMER INT,
SALES_PERSON INT,
PRIMARY KEY (ID),
FOREIGN KEY (CAR) REFERENCES Cars(ID),
FOREIGN KEY (CUSTOMER) REFERENCES Customers(ID),
FOREIGN KEY (SALES_PERSON) REFERENCES Sales_People(ID));
