INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("3K096I98581DHSNUP", "Volkswagen", "Tiguan", 2019, "Blue");
INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("ZM8G7BEUQZ97IH46V", "Peugeot", "Rifter", 2019, "Red");
INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("RKXVNNIHLVVZOUB4M", "Ford", "Fusion", 2018, "White");
INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("HKNDGS7CU31E9Z7JW", "Toyota", "RAV4", 2018, "Silver");
INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("DAM41UDN3CHU2WVF6", "Volvo", "V60", 2019, "Gray");
INSERT INTO Cars (CAR_ID, MANUFACTURER, MODEL, CAR_YEAR, COLOUR)
VALUES ("DAM41UDN3CHU2WVF6", "Volvo", "V60 Cross Country", 2019, "Gray");

INSERT INTO Customers (CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER, EMAIL, ADDRESS, CITY, STATE, COUNTRY, POST_CODE)
VALUES (20001, "Abraham Lincoln", "+1 305 907 7086", 'n/a', "120 SW 8th St", "Miami", "Florida", "United States", "33130");
INSERT INTO Customers (CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER, EMAIL, ADDRESS, CITY, STATE, COUNTRY, POST_CODE)
VALUES (30001, "Napoléon Bonaparte", "+33 1 79 75 40 00", 'n/a', "40 Rue du Colisée", "Paris", "Ile de France", "France", "75008");

INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00001, "Petey Cruiser", "Madrid");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00002, "Anna Sthesia", "Barcelona");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00003, "Paul Molive", "Berlin");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00004, "Gail Forcewind", "Paris");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00005, "Paige Turner", "Mimia");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00006, "Bob Frapples", "Mexico City");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00007, "Walter Melon", "Amsterdam");
INSERT INTO Sales_People (STAFF_ID, SALESPERSON_NAME, STORE_NAME)
VALUES (00008, "Shonda Leer", "Sao Paulo")

INSERT INTO Invoices (INVOICE_NUMBER, INVOICE_DATE, CAR, CUSTOMER, SALES_PERSON)
VALUES (852399038, '22-08-2018', 0 , 1, 3);
INSERT INTO Invoices (INVOICE_NUMBER, INVOICE_DATE, CAR, CUSTOMER, SALES_PERSON)
VALUES (731166526, "2018-12-31", 3 , 2, 5);
INSERT INTO Invoices (INVOICE_NUMBER, INVOICE_DATE, CAR, CUSTOMER, SALES_PERSON)
VALUES (271135104, "2019-01-22", 2 , 3, 7);
