# Introduction To Probability
## Challenge 1

A and B are events of a probability space with $(\omega, \sigma, P)$ such that $P(A) = 0.3$, $P(B) = 0.6$ and $P(A \cap B) = 0.1$

Which of the following statements are false?
* $P(A \cup B) = 0.6$
* $P(A \cap B^{C}) = 0.2$
* $P(A \cap (B \cup B^{C})) = 0.4$
* $P(A^{C} \cap B^{C}) = 0.3$
* $P((A \cap B)^{C}) = 0.9$

"""
* Answers:
* First we check if A and B are dependent or independent
* If independent,  P(A∩B) = P(A) * P(B) 
* For our case  P(A∩B) = 0.3*0.6=0.18 which is not equal to 0.1
* so A and B are dependent events

*this statement is false 𝑃(𝐴∪𝐵)=0.6  because correct answer is P(A∪B) = P(A) + P(B) - P(A∩B)=0.3+0.6-0.1=0.8

*this statement is false $𝑃(𝐴∩𝐵^{C})=0.2$ because correct answer is 0.12

*$P(𝐵^{C})=1-P(B)=1-0.6=0.4$ then $P(A \cap B^{C})=0.3*0.4=0.12$

*this statement is false  $P(A \cap (B \cup B^{C})) = 0.4$ because correct answer is 0.3 

*$P(B \cup B^{C}) = P(B) + P(B^{C})=0.6+0.4=0.10$
* $P(A \cap (B \cup B^{C})) = P(A) * P(B \cup B^{C})=0.3*0.1=0.3$

*this statement is false $P(A^{C} \cap B^{C}) = 0.3$ because correct answer is 0.28

*$P(A^{C} )=1-P(A)=1-0.3=0.7$
* $P(A^{C} \cap B^{C})=0.7*0.4=0.28$ 


*this statement is correct $P((A \cap B)^{C}) = 0.9$ 
* $(A \cap B)^{C}=1-0.1=0.9$
 
"""

In [3]:
#paolo: a few of above questions are not correct-check solutions 
# and/or lets talk about it
#paolo:2nd statement true- third false, forth false, fifth true
#paolo: suggestion is to draw the different situations

## Challenge 2
There is a box with 10 white balls, 12 red balls and 8 black balls. Calculate the probability of:
* Taking a white ball out.
* Taking a white ball out after taking a black ball out.
* Taking a red ball out after taking a black and a red ball out.
* Taking a red ball out after taking a black and a red ball out with reposition.

**Hint**: Reposition means putting back the ball into the box after taking it out.


* Answers:
* total number of balls = 30
* Taking a white ball out.P(w)=10/30
* P(r)=12/30
* P(b)=8/30
* Taking a white ball out after taking a black ball out. P(w|b)=8/30*10/29=0.26*0.34=0.0884
* Taking a black and red ball out = P(b|r)=12/30*8/29=0.4*0.27=0.108
* Taking a red ball out after taking a black and a red ball out. P(r)| P(b|r)=12/28*0.108=0.42*0.108=0.045
* Taking a black and red ball out with reposition= P(b|r)=12/30*8/30=0.4*0.266=0.106
* Taking a red ball out after taking a black and a red ball out with reposition. P(r)| P(b|r)=12/30*0.106=0.4*0.106=0.042


In [ ]:
#paolo: a few of the results are not correct- lets talk about it 
# and/or check solutions
#paolo: nice use of markdown

## Challenge 3

You are planning to go on a picnic today but the morning is cloudy. You hate rain so you don't know whether to go out or stay home! To help you make a decision, you gather the following data about rainy days:

* 50% of all rainy days start off cloudy!
* Cloudy mornings are common. About 40% of days start cloudy. 
* This month is usually dry so only 3 of 30 days (10%) tend to be rainy. 

What is the chance of rain during the day?

"""
* Answer:
* P(Cloud|Rain)=probability of cloud given that rain happens = 1/2 rainy days start cloudy=0.5
* P(cloud)=2/5 days have cloudy mornings=0.4
* P(rain)=3/30 days rainy this month=0.1

* P(Rain|Cloud)= probability of rain given that it is cloudy=(P(Rain)*P(Cloud/Rain))/P(Cloud)=(0.1*0.5)/0.4=0.05/0.4=0.125

"""
#paolo: yes!

## Challenge 4

One thousand people were asked through a telephone survey whether they thought more street lighting is needed at night or not.

Out of the 480 men that answered the survey, 324 said yes and 156 said no. On the other hand, out of the 520 women that answered, 351 said yes and 169 said no. 

We wonder if men and women have a different opinions about the street lighting matter. Is gender relevant or irrelevant to the question?

Consider the following events:
- The answer is yes, so the person that answered thinks that more street lighting is needed.
- The person who answered is a man.

We want to know if these events are independent, that is, if the fact of wanting more light depends on whether one is male or female. Are these events independent or not?

**Hint**: To clearly compare the answers by gender, it is best to place the data in a table.

In [2]:
# your code here
#Bernoulli discrete random variable
from pandas import DataFrame

import pandas as pd
men=[324,156]
women=[351,169]
column_names = ["Men", "Women"]
df = pd.DataFrame(columns = column_names)
df = pd.DataFrame(list(zip(men, women)), 
               columns =["Men", "Women"]) 
df.insert(0, "Answer", ['Yes','No'], True) 
df['Total']=df['Men']+df['Women']
df

Answer  Men  Women  Total
0    Yes  324    351    675
1     No  156    169    325

"""
* P(m Yes)=324/1000=0.32
* P(m No)=156/1000=0.15
* P(w Yes)=351/1000=0.35
* P(w No)=169/1000=0.17
* P(m and w Yes)=(324+351)/1000=0.67

* Events A and B are independent if the equation P(A∩B) = P(A) · P(B) holds true. 
* P(m Yes) * P (w Yes)=0.32*0.35=0.11
* but before we saw that P(m and w Yes)=(324+351)/1000=0.67, the equation does not hold true, therefore the events are dependent
"""

In [ ]:
#paolo: this result is not correct- you could check if the percentage of women 
# who say yes is the same as the percentage of men who say yes
